### PR TITLE
Invalid project name (Intellij idea)

### PR DESCRIPTION
**Pull request by GurteX**
Fix -> Once you get https://github.com/3arthqu4ke/Phobot.git it sets the folder to Phobot, and its phobot in gadle, creates an error

### CODE REVIEW

**Comment by GurteX** [comment]
This is to hopefully deal with any issues when getting the client from vcs

**Comment by 3arthqu4ke** [comment]
Whats the error?

**Comment by GurteX** [comment]
> Whats the error?

Its with the package name, had to fix it in my case, with the exact version from vcs (.git) cant really remember what exactly it said, but it was smthn like IllegalStateException abstract entity Phobot ... something

**Comment by GurteX** [comment]
> > Whats the error?
> 
> Its with the package name, had to fix it in my case, with the exact version from vcs (.git) cant really remember what exactly it said, but it was smthn like IllegalStateException abstract entity Phobot ... something

Here you can really just test it yourself, by going in intellij idea, clicking get from vcs, pasting in this repo url, and hit sync button

**Comment by GurteX** [comment]
and about classifier, after i fixed the package issue, another appeared, and after removing these 2 lines i was able to sync the project.

**Comment by 3arthqu4ke** [comment]
This is an Intellij issue: https://youtrack.jetbrains.com/issue/IDEA-317606/Changing-only-the-case-of-the-Gradle-root-project-name-causes-exception-while-importing-project-java.lang.IllegalStateException

Just clone into the correct folder

Edit: Renamed repo so this does not happen

**Comment by GurteX** [comment]
A problem occurred evaluating root project 'phobot'.
> Could not find method classifier() for arguments [dev-shadow] on task ':fabric:shadowJar' of type com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.

**Pull request closed without merging**
